---

api_id: 25351766
api_hash: a15ed753d880cc573264e198ea25ce6b
app_short_name: sadsadasdsa
phone_number: "+994602478446"

splay: 50

messages:
  one: |
    âœ…MÃœKÆMMÆL YENÄ° SÄ°STEMâœ…
    ğŸ‡29.12.2023ğŸ‡
    Ä°lk qatilan hÉ™r zaman qazanirÂ Â Â Â Â Â  ğŸ†YATRÄ°MSÄ°Z 4$ KAZANğŸ†
    ğŸ‡ğŸ‡ğŸ‡ğŸ‡ğŸ‡ğŸ‡ğŸ‡ğŸ‡ğŸ‡ğŸ‡ğŸ‡
    YATRÄ°M ETMÆDÆN REFAL YATRÄ°MÄ°NÄ° ANÄ°NDA Ã‡ÆKÆNDÆ BÄ°NANCE HESABÄ°NA KÃ–Ã‡ÃœR
    LV 1-10$ DEPOZÄ°T-1$ QAZANC
    DAHA YÃœKSÆK DEPOZÄ°T YUKSÆK QAZANC.
    âœ…âœ…âœ…âœ…âœ…âœ…âœ…âœ…âœ…
    Ã‡ixariÅŸ almkÅŸam 5dÉ™q hesaba Ã§atÄ±r.
    Kayit linkğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡
    https://m1-ai.cc/7GBkFC
    
    ğŸ“£Min depozit 10$
    ğŸ“£Min Ã§ekim 1$
    ğŸ“£Para Ã§ekim aninda Binace cÃ¼zdanina yatÄ±rÄ±lÄ±r
    ğŸ“£10$ gÃ¼ndÉ™lik 1 dolar qazanc
    ğŸ“£Pul Ã§ixariÅŸ faizi yoxdur
    ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£
    Qeydiyyat linkğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡
    https://m1-ai.cc/7GBkFC
    ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£
    Qrup:ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡
    https://t.me/+ZqHxPr_RI94xYWFh
    ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£ğŸ’£
    4$ Yatrimsiz qazanmaq Ã¼Ã§Ã¼n
    ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡
    ğŸ†Kanala qatil like et ekrani Ã§É™k sonra sayta yerlÉ™ÅŸdir yoxlaniÅŸ vÉ™ 1$ bonus
    ğŸ†Ã–z É™linizdÉ™ saytin telfon ilÉ™ ekran gÃ¶rntsÃ¼n Ã§É™kin yerlÉ™ÅŸdrin 3$ bonus alin.
    ğŸ†4$ bonusa 6$ depozit edin vÉ™ Vip 1 alin 60 gÃ¼n 1$ qazanin.
    â¬†ï¸â¬†ï¸â¬†ï¸â¬†ï¸â¬†ï¸â¬†ï¸â¬†ï¸â¬†ï¸â¬†ï¸â¬†ï¸â¬†ï¸

raid:
  globalinksharing:
    message_type: one
    wait_interval: 275
  onlineqazanc3:
    message_type: one
    wait_interval: 280
  onlineqazanc369:
    message_type: one
    wait_interval: 285
  Online_Qazanmaq2023:
    message_type: one
    wait_interval: 290
  Business_FikirAl:
    message_type: one
    wait_interval: 295 
  qazancqrupu145:
    message_type: one
    wait_interval: 300 
  online_qazancc:
    message_type: one
    wait_interval: 305 
  pulqazanvip:
    message_type: one
    wait_interval: 310
  onlineqazanccneco:
    message_type: one
    wait_interval: 305  
  onlineqazanc8229:
    message_type: one
    wait_interval: 315  
  qazancqrupu:
    message_type: one
    wait_interval: 320
  Pulqazan32:
    message_type: one
    wait_interval: 325
  HmR5E4ANaM1NmFi:
    message_type: one
    wait_interval: 330
  onlinereklamm:
    message_type: one
    wait_interval: 335
  IXFYVjisVQ8wNTBi:
    message_type: one
    wait_interval: 340
  OldlarGroups:
    message_type: one
    wait_interval: 345
  Online_Qazanc777:
    message_type: one
    wait_interval: 350
  onlineqazanc8229:
    message_type: one
    wait_interval: 355 
    increase_wait_interval: 60
    total_messages: 10
    image: images/cd.jpg
random_message_format: |
  lambda rm1, rm2 : rm1 + " & " + rm2 + "!"

random_message:
- a
- b
- c
- d